import React from 'react';
import CustomTable from './CustomTable/CustomTable';

const HumanResources = () => {
  const dataHR = [
    {
      key: '1',
      fullName: 'Aybəniz Əliyeva',
      username: '-',
      gender: 'Qadın',
      age: 24,
      university: 'ADİU',
      faculty: 'Texnologiya Mühəndisliyi',
      degree: 'Magistr',
      course: 'Məzun',
      email: '-',
      address: '-',
    },
    {
      key: '2',
      fullName: 'Elnarə Veyisova',
      username: '-',
      gender: 'Qadın',
      age: 24,
      university: 'ADİU',
      faculty: 'İqtisadiyyatın tənzimlənməsi',
      degree: 'Magistr',
      course: 2,
      email: '-',
      address: '-',
    },
    {
      key: '3',
      fullName: 'Sumanə Həşimova',
      username: '-',
      gender: 'Qadın',
      age: 19,
      university: 'BDU',
      faculty: 'İqtisadiyyat',
      degree: 'Bakalavr',
      course: 3,
      email: '-',
      address: '-',
    },
    {
      key: '4',
      fullName: 'Sama Aghamammadova',
      username: '-',
      gender: 'Qadın',
      age: 19,
      university: 'UFAZ',
      faculty: 'Kimya Mühəndisliyi',
      degree: 'Bakalavr',
      course: 3,
      email: '-',
      address: '-',
    },
    {
      key: '5',
      fullName: 'Turqay İsgəndərli',
      username: '-',
      gender: 'Kişi',
      age: 21,
      university: 'China University of Petroleum',
      faculty: 'Oil and Gas Well Drilling',
      degree: 'Magistr',
      course: 1,
      email: '-',
      address: '-',
    },
    {
      key: '6',
      fullName: 'Gülhanə Nəcəfli',
      username: '-',
      gender: 'Qadın',
      age: 21,
      university: 'BDU',
      faculty: 'Coğrafiya',
      degree: 'Bakalavr',
      course: 'Məzun',
      email: '-',
      address: '-',
    },
    {
      key: '7',
      fullName: 'Əli Səlimli',
      username: '-',
      gender: 'Kişi',
      age: 19,
      university: 'ADİU',
      faculty: 'İqtisadiyyat',
      degree: 'Bakalavr',
      course: 3,
      email: '-',
      address: '-',
    },
    {
      key: '8',
      fullName: 'Şəlalə Nəzərova',
      username: '-',
      gender: 'Qadın',
      age: 23,
      university: 'ADİU',
      faculty: 'İnsan resurslarının idarə edilməsi',
      degree: 'Magistr',
      course: 1,
      email: '-',
      address: '-',
    },
    {
      key: '9',
      fullName: 'Nərmin Yaqubova ',
      username: '-',
      gender: 'Qadın',
      age: 23,
      university: 'ADİU',
      faculty: 'İnnovasiyaların və layihələrin idarə edilməs',
      degree: 'Magistr',
      course: 1,
      email: '-',
      address: '-',
    },
    {
      key: '10',
      fullName: 'Minayə Məmmədova',
      username: '-',
      gender: 'Qadın',
      age: 22,
      university: 'ADİU',
      faculty: 'Makroiqtisadi siyasət',
      degree: 'Magistr',
      course: 1,
      email: '-',
      address: '-',
    },
    {
      key: '11',
      fullName: 'Mahira Aliyeva',
      username: '-',
      gender: 'Qadın',
      age: 21,
      university: 'ADNSU',
      faculty: 'HR Management',
      degree: 'Magistr',
      course: 1,
      email: '-',
      address: '-',
    },
    {
      key: '12',
      fullName: 'Aytac Məmmədova',
      username: '-',
      gender: 'Qadın',
      age: 20,
      university: 'APDİA',
      faculty: 'İqtisadiyyat',
      degree: 'Bakalavr',
      course: 4,
      email: '-',
      address: '-',
    },
    {
      key: '13',
      fullName: 'Elmira Qardaşbəyova',
      username: '-',
      gender: 'Qadın',
      age: 21,
      university: 'ADİU',
      faculty: 'Menecment',
      degree: 'Bakalavr',
      course: 4,
      email: '-',
      address: '-',
    },
  ];
  return (
    <div>
      <h3 style={{ color: 'white' }}>Human Resources</h3>
      <CustomTable>{dataHR}</CustomTable>
    </div>
  );
};

export default HumanResources;
