import React from 'react';
import CustomTable from './CustomTable/CustomTable';

const Information = () => {
  const dataIT = [
    {
      key: '1',
      fullName: 'Günel Ağakişiyeva',
      username: '-',
      gender: 'Qadın',
      age: 19,
      university: 'UFAZ',
      faculty: 'Geofizika mühəndiliyi',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '2',
      fullName: 'Qönçə Memmedova',
      username: '-',
      gender: 'Qadın',
      age: 21,
      university: 'BMU',
      faculty: 'IT',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '3',
      fullName: 'Kənan Əhmədli',
      username: '-',
      gender: 'Kişi',
      age: 21,
      university: 'ADNSU',
      faculty: 'Proselərin Avtomatlaşdırlması ',
      degree: 'Magistr',
      course: 2,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '4',
      fullName: 'Fərhad Əmrah',
      username: 'farhadamrah',
      gender: 'Kişi',
      age: 23,
      university: 'ATU',
      faculty: 'Kompüter Mühəndisliyi',
      degree: 'Bakalavr',
      course: 'Məzun',
      department: 'IT',
      email: 'emferhad17631@sabah.edu.az',
      address: 'Bakı',
    },
    {
      key: '5',
      fullName: 'Günel Kişiyeva',
      username: '-',
      gender: 'Qadın',
      age: 19,
      university: 'ADNSU',
      faculty: 'Sistem Mühəndisliy',
      degree: 'Bakalavr',
      course: 2,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '6',
      fullName: 'Ömər Şükürov',
      username: '-',
      gender: 'Kişi',
      age: 19,
      university: 'ADNSU',
      faculty: 'İnformasiya Təhlükəsizliyi',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '7',
      fullName: 'Rəşad Əzimov',
      username: '-',
      gender: 'Kişi',
      age: 19,
      university: 'ADNSU',
      faculty: 'Mexatronika mühəndisliyi',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '8',
      fullName: 'Nigar Babayeva',
      username: '-',
      gender: 'Qadın',
      age: 18,
      university: 'ADİU',
      faculty: 'Pazarlama',
      degree: 'Bakalavr',
      course: 2,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '9',
      fullName: 'Abuzər Kərimzadə',
      username: '-',
      gender: 'Kişi',
      age: 18,
      university: 'BMU',
      faculty: 'İT mühəndisliyi',
      degree: 'Bakalavr',
      course: 2,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '10',
      fullName: 'Jalə Bağırova',
      username: '-',
      gender: 'Qadın',
      age: 19,
      university: 'BDU',
      faculty: 'Riyaziyyat',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '11',
      fullName: 'Həsən Qəhrəmanlı ',
      username: '-',
      gender: 'Kişi',
      age: 22,
      university: 'ADİU',
      faculty: 'Menecment',
      degree: 'Menecment',
      course: 1,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '12',
      fullName: 'Rəmziyyə Əliyeva',
      username: '-',
      gender: 'Qadın',
      age: 20,
      university: 'BMU',
      faculty: 'İnformasiya texnologiyaları',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '13',
      fullName: 'Zivər Haqverdiyeva',
      username: '-',
      gender: 'Qadın',
      age: 19,
      university: 'UFAZ',
      faculty: 'Geofizika Mühəndisliyi',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
    {
      key: '14',
      fullName: 'Məhəmməd Nəbizadə',
      username: '-',
      gender: 'Kişi',
      age: 18,
      university: 'UFAZ',
      faculty: 'Geofizika Mühəndisliyi',
      degree: 'Bakalavr',
      course: 3,
      department: 'IT',
      email: '-',
      address: '-',
    },
  ];
  return (
    <div>
      <h3 style={{ color: 'white' }}>Information Technology</h3>
      <CustomTable>{dataIT}</CustomTable>
    </div>
  );
};

export default Information;
